const state={screen:1,day:1,tasks:0,energy:78};let timerInterval=null;
function goTo(n){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById('screen-'+n).classList.add('active');state.screen=n;window.scrollTo({top:0,behavior:'smooth'});save();}
document.querySelectorAll('.options').forEach(group=>{group.addEventListener('click',e=>{if(e.target.tagName!=='BUTTON')return;if(group.classList.contains('single'))group.querySelectorAll('button').forEach(b=>b.classList.remove('selected'));e.target.classList.toggle('selected');});});
function startReset(){state.day=1;state.tasks=0;state.energy=78;save();resetTasks();goTo(5);}
function resetTasks(){document.querySelectorAll('#tasks input').forEach(i=>{i.checked=false;i.parentElement.classList.remove('done')});taskChanged();}
function taskChanged(){const boxes=[...document.querySelectorAll('#tasks input')];const done=boxes.filter(x=>x.checked).length;state.tasks=done;const pct=Math.round(done/boxes.length*100);document.getElementById('percent').textContent=pct+'%';document.getElementById('progressBar').style.width=pct+'%';boxes.forEach(x=>x.parentElement.classList.toggle('done',x.checked));state.energy=Math.min(100,78+done*4);document.getElementById('energyValue').textContent=state.energy+' / 100';save();}
function save(){localStorage.setItem('reset30',JSON.stringify(state));}
function load(){try{const x=JSON.parse(localStorage.getItem('reset30'));if(x)Object.assign(state,x)}catch(e){}}
function resetApp(){if(confirm('Tem certeza que deseja reiniciar seu RESET 30?')){localStorage.removeItem('reset30');location.reload();}}
function buildCalendar(){const c=document.getElementById('calendar');if(!c)return;for(let i=1;i<=30;i++){const s=document.createElement('span');s.textContent=i;s.className=i<state.day?'done':i===state.day?'partial':'';c.appendChild(s)}}
function startTimer(title){clearInterval(timerInterval);const box=document.getElementById('timerBox'),titleEl=document.getElementById('timerTitle'),timeEl=document.getElementById('timer'),bar=document.getElementById('timerBar');box.classList.remove('hidden');titleEl.textContent=title;let left=120;function tick(){const m=String(Math.floor(left/60)).padStart(2,'0'),s=String(left%60).padStart(2,'0');timeEl.textContent=m+':'+s;bar.style.width=((120-left)/120*100)+'%';if(left<=0){clearInterval(timerInterval);titleEl.textContent='⚡ IMPULSO QUEBRADO';timeEl.textContent='CONCLUÍDO';bar.style.width='100%';state.energy=Math.min(100,state.energy+5);save();return}left--}tick();timerInterval=setInterval(tick,1000);}
load();document.getElementById('dayLabel').textContent='DIA '+String(state.day).padStart(2,'0')+' / 30';document.getElementById('streak').textContent=state.day;buildCalendar();taskChanged();